In [4]:
import numpy as np


# 실습 과제1: NumPy를 활용한 행렬 변형 실습

## 문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.


In [45]:
N = 6
M = 5
A = np.random.randn(N, M)  
print(A.shape)



(6, 5)


## 문제 2: 새로운 축 추가

행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

In [46]:
B = A[:, np.newaxis, :]
print(B)

[[[-0.28707643 -0.48467731 -1.10813596  1.24143534 -1.29047474]]

 [[-0.02037033  2.13348208 -0.43852167 -0.94090112 -1.70726216]]

 [[ 0.71162663  1.76180288 -0.9499854   0.50600477  1.51962849]]

 [[ 0.59695962  1.43965979 -1.02175053  0.0400135   0.02699811]]

 [[ 0.99380854 -1.07905662  0.40856017 -0.08053328 -0.2090343 ]]

 [[ 0.4381733   0.83242013 -0.4830147   0.41111627 -1.85477394]]]


문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

In [47]:
B[2,0:4] = 0.3
B[2,0:4]

array([[0.3, 0.3, 0.3, 0.3, 0.3]])


문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

In [48]:
C = A[np.newaxis, :, :]
C.shape

(1, 6, 5)

In [49]:
D = A[:,:,np.newaxis]
D.shape
print(D)

[[[-0.28707643]
  [-0.48467731]
  [-1.10813596]
  [ 1.24143534]
  [-1.29047474]]

 [[-0.02037033]
  [ 2.13348208]
  [-0.43852167]
  [-0.94090112]
  [-1.70726216]]

 [[ 0.3       ]
  [ 0.3       ]
  [ 0.3       ]
  [ 0.3       ]
  [ 0.3       ]]

 [[ 0.59695962]
  [ 1.43965979]
  [-1.02175053]
  [ 0.0400135 ]
  [ 0.02699811]]

 [[ 0.99380854]
  [-1.07905662]
  [ 0.40856017]
  [-0.08053328]
  [-0.2090343 ]]

 [[ 0.4381733 ]
  [ 0.83242013]
  [-0.4830147 ]
  [ 0.41111627]
  [-1.85477394]]]



문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.