p.135~140

In [1]:
import numpy as np
import pandas as pd

In [2]:
vals1 = np.array([1, None, 2, 3])
vals1

array([1, None, 2, 3], dtype=object)

In [3]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [5]:
vals2 = np.array([1, np.nan, 3,4])
vals2.dtype

dtype('float64')

In [7]:
1 + np.nan
0 * np.nan

nan

In [9]:
vals2.sum(), vals2.min(), vals2.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [10]:
np.nansum(vals2)

np.float64(8.0)

In [11]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [12]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [14]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

In [15]:
pd.Series([1, np.nan, 2, None, pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [16]:
data = pd.Series([1,np.nan,'hello',None])
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [17]:
data[data.notnull()]


0        1
2    hello
dtype: object

In [18]:
data.dropna()

0        1
2    hello
dtype: object

In [19]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4,6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [20]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [21]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [23]:
df[3]=np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [24]:
df.dropna(axis='rows', thresh=3)

0    1  2   3
1  2.0  3.0  5 NaN

In [25]:
# 인덱스에 맞게 리스트랑 대입됨
data= pd.Series([1, np.nan, 2, None,3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [26]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [27]:
data.fillna(method='ffill')

C:\Users\user\AppData\Local\Temp\ipykernel_12804\1844443866.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')


a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [28]:
pip install yfinance

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 0.0/949.2 kB ? eta -:--:--
     ------------------------------------- 949.2/949.2 kB 22.2 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 1.6/1.6 MB 29.3 MB/s eta 0:00:00
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15703 sha256=3e7f1181eb77c21c8c8ca2daae3427016925257fdd2d5ad9c164dffc6d4faf1d
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\98\75\bc\9eaa3cdeaaca347bab26c7e83a7e2

  DEPRECATION: Building 'multitasking' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'multitasking'. Discussion can be found at https://github.com/pypa/pip/issues/6334


In [30]:
import yfinance as yf
yf.__version__

'0.2.65'

In [31]:
yf.download(['MSFT','AAPL','GOOG'], period='1mo')

C:\Users\user\AppData\Local\Temp\ipykernel_12804\3974052729.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  yf.download(['MSFT','AAPL','GOOG'], period='1mo')
[*********************100%***********************]  3 of 3 completed


Price            Close                                High              \
Ticker            AAPL        GOOG        MSFT        AAPL        GOOG   
Date                                                                     
2025-06-20  201.000000  167.729996  477.399994  201.699997  175.365005   
2025-06-23  201.500000  166.009995  486.000000  202.300003  168.479996   
2025-06-24  200.300003  167.740005  490.109985  203.440002  169.250000   
2025-06-25  201.559998  171.490005  492.269989  203.669998  173.360001   
2025-06-26  201.000000  174.429993  497.450012  202.639999  174.649994   
2025-06-27  201.080002  178.270004  495.940002  203.220001  178.839996   
2025-06-30  205.169998  177.389999  497.410004  207.389999  181.580002   
2025-07-01  207.820007  176.910004  492.049988  210.190002  177.220001   
2025-07-02  212.440002  179.759995  491.089996  213.339996  179.934998   
2025-07-03  213.550003  180.550003  498.839996  214.649994  180.770004   
2025-07-07  209.949997  177.559998  497.720001  216.229996  180.339996   
2025-07-08  210.009995  175.160004  496.619995  211.429993  178.789993   
2025-07-09  211.139999  177.660004  503.510010  211.330002  180.279999   
2025-07-10  212.410004  178.699997  501.480011  213.479996  179.589996   
2025-07-11  211.160004  181.309998  503.320007  212.130005  182.610001   
2025-07-14  208.619995  182.809998  503.019989  210.910004  184.729996   
2025-07-15  209.110001  183.100006  505.820007  211.889999  185.410004   
2025-07-16  210.160004  183.770004  505.619995  212.399994  185.335007   
2025-07-17  210.020004  184.699997  511.700012  211.800003  185.186996   
2025-07-18  211.179993  185.940002  510.049988  211.789993  187.360001   

Price                          Low                                Open  \
Ticker            MSFT        AAPL        GOOG        MSFT        AAPL   
Date                                                                     
2025-06-20  483.459991  196.860001  166.270004  476.869995  198.240005   
2025-06-23  487.750000  198.960007  163.330002  472.510010  201.630005   
2025-06-24  491.850006  200.199997  166.910004  486.799988  202.589996   
2025-06-25  494.559998  200.619995  168.561005  489.390015  201.449997   
2025-06-26  498.040009  199.460007  170.860001  492.809998  201.429993   
2025-06-27  499.299988  200.000000  172.710007  493.029999  201.889999   
2025-06-30  500.760010  199.259995  175.500000  495.329987  202.009995   
2025-07-01  498.049988  206.139999  174.660004  490.980011  206.669998   
2025-07-02  493.500000  208.139999  176.089996  488.700012  208.910004   
2025-07-03  500.130005  211.809998  178.190002  493.440002  212.149994   
2025-07-07  498.750000  208.800003  176.639999  495.230011  212.679993   
2025-07-08  498.200012  208.449997  173.919998  494.109985  210.100006   
2025-07-09  506.779999  207.220001  173.880005  499.739990  209.529999   
2025-07-10  504.440002  210.029999  175.740005  497.750000  210.509995   
2025-07-11  505.029999  209.860001  177.541000  497.799988  210.570007   
2025-07-14  503.970001  207.539993  180.710999  501.029999  209.929993   
2025-07-15  508.299988  208.919998  182.389999  502.790009  209.220001   
2025-07-16  506.720001  208.639999  183.080002  501.890015  210.300003   
2025-07-17  513.369995  209.589996  181.500000  505.619995  210.570007   
2025-07-18  514.640015  209.699997  184.729996  507.429993  210.869995   

Price                                 Volume                      
Ticker            GOOG        MSFT      AAPL      GOOG      MSFT  
Date                                                              
2025-06-20  174.865005  482.230011  96813500  55402600  37576200  
2025-06-23  167.320007  478.209991  55814300  36975600  24864000  
2025-06-24  167.684998  488.950012  54064000  27310300  22305600  
2025-06-25  168.649994  492.040009  39525700  23627400  17495100  
2025-06-26  173.384995  492.980011  50799100  25909100  21578900  
2025-06-27  174.630005  497.549988  73188600  74053100  34

In [35]:
df = pd.read_csv('iris.csv')
df.head()


sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [37]:
index=pd.MultiIndex.from_product([['a','c','b'],
                                  [1,2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.297863
      2      0.523999
c     1      0.732999
      2      0.094904
b     1      0.099348
      2      0.323590
dtype: float64

In [38]:
import pandas as pd
import numpy as np

In [40]:
def make_df(cols, ind):
    data = {c: [str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)

make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

p.161~167

In [45]:
# numpy 배열 연결
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x=[[1,2],[3,4]]
np.concatenate([x,x], axis=1)
np.concatenate([x,x], axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [47]:
ser1 = pd.Series(['A','B','C'], index=[1,2,3])
ser2 = pd.Series(['D','E','F'], index=[4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [50]:
df_state = pd.read_csv('state-abbrevs.csv')
df_state.head(), df_state.shape

(        state abbreviation
 0     Alabama           AL
 1      Alaska           AK
 2     Arizona           AZ
 3    Arkansas           AR
 4  California           CA,
 (51, 2))

In [49]:
df_areas = pd.read_csv('state-areas.csv')
df_areas.head()

state  area (sq. mi)
0     Alabama          52423
1      Alaska         656425
2     Arizona         114006
3    Arkansas          53182
4  California         163707

In [ ]:
df_pop = pd.read_csv('state-population.csv')
df_pop.head()